# Generated by Django 5.0.6 on 2025-02-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenAIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(help_text='Text to be passed to ChatGPT as extra context prior to processing user input', max_length=255)),
            ],
            options={
                'verbose_name': 'Chicken AI Context',
                'verbose_name_plural': 'Chicken AI Context',
            },
        ),
        migrations.CreateModel(
            name='EggAIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(help_text='Text to be passed to ChatGPT as extra context prior to processing user input', max_length=255)),
            ],
            options={
                'verbose_name': 'Egg AI Context',
                'verbose_name_plural': 'Egg AI Context',
            },
        ),
        migrations.AlterModelOptions(
            name='dragonaicontext',
            options={'verbose_name': 'Dragon AI Context', 'verbose_name_plural': 'Dragon AI Context'},
        ),
        migrations.AlterModelOptions(
            name='hedgehogaicontext',
            options={'verbose_name': 'Hedgehog AI Context', 'verbose_name_plural': 'Hedgehog AI Context'},
        ),
        migrations.AlterModelOptions(
            name='wolfaicontext',
            options={'verbose_name': 'Wolf AI Context', 'verbose_name_plural': 'Wolf AI Context'},
        ),
    ]
